# Generated by Django 2.2.2 on 2019-07-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0024_full_name_slug_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('snippet', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='dispatch.Tag')),
            ],
        ),
    ]
